[project]
name = "apps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sminamiafb9", email = "204111097+sminamiafb9@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "gradio>=6.26.0",
    "uvicorn[standard]>=0.52.4",
    "websocket-client>=1.9.0",
]

[project.scripts]
dbx-apps = "apps.main:entry_point"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
exclude-newer = "7 days"

[[tool.uv.index]]
url = "https://pypi.flatt.tech/simple/"
default = true
